apiVersion: v1
kind: Pod
metadata:
  name: posts
spec:
  containers: 
    - name: posts
      image: richdg4/posts:latest
      imagePullPolicy: Never
      env:
        - name: EVENT_BUS_URL
          value: http://event-bus:4005